*** empty log message ***

diff --git a/docs/wxparaver b/docs/wxparaver
--- a/docs/wxparaver
+++ b/docs/wxparaver
@@ -8,19 +8,19 @@ export PARAVER_HOME=${PARAVER_HOME%/bin}
 #  echo "Please set \$PARAVER_HOME to the wxparaver installation root directory"
 #  exit 1
 
-if ! [ -d "${PARAVER_HOME}/lib/paraver-kernel" ] ; then
-  echo "paraver-kernel libraries not found in \$PARAVER_HOME/lib/paraver-kernel/"
+if [ -d "${PARAVER_HOME}/lib/paraver-kernel" ] ; then
+  LIB_DIR=lib
+elif [ -d "${PARAVER_HOME}/lib64/paraver-kernel" ] ; then
+  LIB_DIR=lib64
+else
+  echo "paraver-kernel libraries not found in \$PARAVER_HOME/{lib,lib64}/paraver-kernel/"
   exit 1
-
-##elif ! [ -d ${PARAVER_HOME}/lib/wxparaver ] ; then
-##  echo "wxparaver libraries not found in \$PARAVER_HOME/lib/wxparaver/"
-##  exit 1
-
-elif ! [ -e "${PARAVER_HOME}/bin/wxparaver.bin" ] ; then
-  echo "wxparaver binary not found in \$PARAVER_HOME/bin/"
-  exit 1
-  
 fi
 
-LD_LIBRARY_PATH="${PARAVER_HOME}/lib/ptools_common_files/:${PARAVER_HOME}/lib/paraver-kernel:${PARAVER_HOME}/lib/wxparaver:$LD_LIBRARY_PATH" "${PARAVER_HOME}/bin/wxparaver.bin" "$@"
+if ! [ -e "${PARAVER_HOME}/bin/wxparaver.bin" ] ; then
+  echo "wxparaver binary not found in \$PARAVER_HOME/bin/"
+  exit 1
+fi
+
+LD_LIBRARY_PATH="${PARAVER_HOME}/${LIB_DIR}/ptools_common_files/:${PARAVER_HOME}/${LIB_DIR}/paraver-kernel:${PARAVER_HOME}/${LIB_DIR}/wxparaver:$LD_LIBRARY_PATH" "${PARAVER_HOME}/bin/wxparaver.bin" "$@"
 	
